//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_Lab01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        public int ProductID { get; set; }

        [Display(Name = "ProductName")]
        public string ProductName { get; set; }

        [Display(Name = "SupplierID")]
        public Nullable<int> SupplierID { get; set; }

        [Display(Name = "CategoryID")]
        public Nullable<int> CategoryID { get; set; }

        [Display(Name = "QuantityPerUnit")]
        public string QuantityPerUnit { get; set; }

        [Display(Name = "UnitPrice")]
        public Nullable<decimal> UnitPrice { get; set; }

        [Display(Name = "UnitsInStock")]
        public Nullable<short> UnitsInStock { get; set; }

        [Display(Name = "UnitsOnOrder")]
        public Nullable<short> UnitsOnOrder { get; set; }

        [Display(Name = "ReorderLevel")]
        public Nullable<short> ReorderLevel { get; set; }

        [Display(Name = "Discontinued")]
        public bool Discontinued { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
