//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_Lab01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        public int ProductID { get; set; }

        [Required]
        public string ProductName { get; set; }

        [Required]
        public Nullable<int> SupplierID { get; set; }

        [Required]
        public Nullable<int> CategoryID { get; set; }

        [Required]
        public string QuantityPerUnit { get; set; }

        [Required]
        public Nullable<decimal> UnitPrice { get; set; }

        [Required]
        public Nullable<short> UnitsInStock { get; set; }

        [Required]
        public Nullable<short> UnitsOnOrder { get; set; }

        [Required]
        public Nullable<short> ReorderLevel { get; set; }


        public bool Discontinued { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
